data(tsd)
ts <- ts_data(tsd$y, 10)
ts_head(ts, 3)
samp <- ts_sample(ts, test_size = 5)
io_train <- ts_projection(samp$train)
io_test <- ts_projection(samp$test)
tune <- ts_tune(input_size=c(3:5), base_model = ts_elm(ts_norm_gminmax()), ranges = list(nhid = 1:5, actfun=c('purelin')))
model <- fit(tune, x=io_train$input, y=io_train$output)
