Objetivo: Aplicar normalização adaptativa (média móvel/EMA) para lidar com mudanças de distribuição ao longo do tempo e observar o efeito no alvo.

```{r}
# Normalização Adaptativa Exponencial

# Instalando o pacote (se necessário)
install.packages("tspredit")
```

```{r}
# Carregando os pacotes
library(daltoolbox)
library(tspredit) 
```


```{r}
# Série para estudo

data(tsd)
```

```{r}
# Visualização da série
library(ggplot2)
plot_ts(x=tsd$x, y=tsd$y) + theme(text = element_text(size=16))
```

```{r}
# Janelas deslizantes

sw_size <- 10
ts <- ts_data(tsd$y, sw_size)
ts_head(ts, 3)
summary(ts[,10])
```

```{r}
# Visualização do alvo (t0) após janelamento
library(ggplot2)
plot_ts(y=ts[,10]) + theme(text = element_text(size=16))
```

```{r}
# normalization

preproc <- ts_norm_an()
preproc <- fit(preproc, ts)
tst <- transform(preproc, ts)
ts_head(tst, 3)
summary(tst[,10])
plot_ts(y=ts[1,]) + theme(text = element_text(size=16))
```

Objetivo: Aplicar normalização adaptativa (média móvel/EMA) para lidar com mudanças de distribuição ao longo do tempo e observar o efeito no alvo.
