---
title: "clu_kmeans"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{clu_kmeans}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# DAL Package

## Clustering - Kmeans

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(daltoolbox)
library(dplyr)
library(cluster)
library(factoextra)
```

```{r}
iris <- datasets::iris
```

## General function to test clustering methods

```{r}
test_clustering <- function(model, data, attribute, opt=FALSE) {
  describe(model)
  if (opt) 
    model <- optimize(model, data)    
  clu <- fit(model, data)
  print(table(clu))
  eval <- cluster_evaluation(clu, attribute)
  print(eval$entropy)
}
```

```{r}
# kmeans with k equals 3
test_clustering(cluster_kmeans(k=3), iris[,1:4], iris[,5])
```

```{r}
test_clustering(cluster_kmeans(NULL), iris[,1:4], iris[,5], TRUE)
```

## Influence of normalization in clustering

```{r}
norm_minmax <- fit(minmax(), iris)
iris_minmax <- transform(norm_minmax, iris)
test_clustering(cluster_kmeans(k=8), iris_minmax[,1:4], iris_minmax[,5])
```

```{r}
norm_zscore <- fit(zscore(), iris)
iris_zscore <- transform(norm_zscore, iris)
# kmeans with k equals 8
test_clustering(cluster_kmeans(k=8), iris_zscore[,1:4], iris_zscore[,5])
```
