---
title: "reg_svm"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{reg_svm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# DAL Package

## Regression SVM

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(daltoolbox)
library(e1071)
```

### Dataset for regression analysis

```{r}
library("MASS")
data(Boston)
print(t(sapply(Boston, class)))
head(Boston)
```

```{r}
# for performance issues, you can use matrix
Boston <- as.matrix(Boston)
```

## Building samples (training and testing)

```{r}
# preparing dataset for random sampling
set.seed(1)
sr <- sample_random()
sr <- train_test(sr, Boston)
boston_train = sr$train
boston_test = sr$test
```

### Training

```{r}
model <- reg_svm("medv", epsilon=0.2,cost=40.000)
describe(model)
model <- fit(model, boston_train)

train_prediction <- predict(model, boston_train)
boston_train_predictand = boston_train[,"medv"]
train_eval <- evaluation.regression(boston_train_predictand, train_prediction)
print(train_eval$metrics)
```

### Test

```{r}
test_prediction <- predict(model, boston_test)
boston_test_predictand = boston_test[,"medv"]
test_eval <- evaluation.regression(boston_test_predictand, test_prediction)
print(test_eval$metrics)
```

