---
title: "ts_augment"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ts_augment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# DAL Package

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(daltoolbox)
```

## Time series data augmentation

### Cosine series for studying
```{r}
i <- seq(0, 2*pi+8*pi/50, pi/50)
x <- cos(i)

options(repr.plot.width=6, repr.plot.height=5)  
par(mfrow = c(1, 1))
plot(i, x)
lines(i, x)
```

### sliding windows
```{r}
sw_size <- 10
xw <- ts_data(x, sw_size)
i <- 1:nrow(xw)
y <- xw[,sw_size]

options(repr.plot.width=12, repr.plot.height=5)  
par(mfrow = c(1, 2))
hist(i)
plot(i, y)
lines(i, y)
```

### jitter
```{r}
augment <- jitter()
augment <- fit(augment, xw)
xa <- transform(augment, xw)
idx <- attr(xa, "idx")

options(repr.plot.width=12, repr.plot.height=5)  
par(mfrow = c(1, 2))

hist(idx)
plot(x = i, y = y, main = "cosine")
lines(x = i, y = y, col="black")
for (j in 1:nrow(xa)) {
  lines(x = (idx[j]-sw_size+1):idx[j], y = xa[j,1:sw_size], col="green")
}
```

### wormhole
```{r}
augment <- wormhole()
augment <- fit(augment, xw)
xa <- transform(augment, xw)
idx <- attr(xa, "idx")

options(repr.plot.width=12, repr.plot.height=5)  
par(mfrow = c(1, 2))

hist(idx)
plot(x = i, y = y, main = "cosine")
lines(x = i, y = y, col="black")
for (j in 1:nrow(xa)) {
  lines(x = (idx[j]-sw_size+1):idx[j], y = xa[j,1:sw_size], col="green")
}
```

### stretch
```{r}
augment <- stretch()
augment <- fit(augment, xw)
xa <- transform(augment, xw)
idx <- attr(xa, "idx")

options(repr.plot.width=12, repr.plot.height=5)  
par(mfrow = c(1, 2))

hist(idx)
plot(x = i, y = y, main = "cosine")
lines(x = i, y = y, col="black")
for (j in 1:nrow(xa)) {
  lines(x = (idx[j]-sw_size+1):idx[j], y = xa[j,1:sw_size], col="green")
}
```

### shrink
```{r}
augment <- shrink()
augment <- fit(augment, xw)
xa <- transform(augment, xw)
idx <- attr(xa, "idx")

options(repr.plot.width=12, repr.plot.height=5)  
par(mfrow = c(1, 2))

hist(idx)
plot(x = i, y = y, main = "cosine")
lines(x = i, y = y, col="black")
for (j in 1:nrow(xa)) {
  lines(x = (idx[j]-sw_size+1):idx[j], y = xa[j,1:sw_size], col="green")
}
```

### flip
```{r}
augment <- flip()
augment <- fit(augment, xw)
xa <- transform(augment, xw)
idx <- attr(xa, "idx")

options(repr.plot.width=12, repr.plot.height=5)  
par(mfrow = c(1, 2))

hist(idx)
plot(x = i, y = y, main = "cosine")
lines(x = i, y = y, col="black")
for (j in 1:nrow(xa)) {
  lines(x = (idx[j]-sw_size+1):idx[j], y = xa[j,1:sw_size], col="green")
}
```

