---
title: "ts_filter"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ts_filter}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# DAL Package

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(daltoolbox)
```

## Time series preprocessing

### Noise cosine series for studying
```{r}
i <- seq(0, 2*pi+8*pi/50, pi/50)
x <- cos(i)
noise <- rnorm(length(x), 0, sd(x)/10)

x <- x + noise
x[30] <-rnorm(1, 0, sd(x))

x[60] <-rnorm(1, 0, sd(x))

x[90] <-rnorm(1, 0, sd(x))

options(repr.plot.width=6, repr.plot.height=5)  
par(mfrow = c(1, 1))
plot(i, x)
lines(i, x)
```

### smooth
```{r}
filter <- ts_smooth()
filter <- fit(filter, x)
y <- transform(filter, x)

plot(x = i, y = x, main = "cosine")
lines(x = i, y = x, col="black")
lines(x = i, y = y, col="green")
```

### moving average
```{r}
filter <- ts_ma(3)
filter <- fit(filter, x)
y <- transform(filter, x)

plot(x = i, y = x, main = "cosine")
lines(x = i, y = x, col="black")
lines(x = i, y = y, col="green")
```

### exponential moving average
```{r}
filter <- ts_ema(3)
filter <- fit(filter, x)
y <- transform(filter, x)

plot(x = i, y = x, main = "cosine")
lines(x = i, y = x, col="black")
lines(x = i, y = y, col="green")
```
